# Generated by Django 3.2.11 on 2022-01-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogindexpage',
            old_name='into',
            new_name='intro',
        ),
    ]
