# Generated by Django 3.2.11 on 2022-01-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220128_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'home page', 'verbose_name_plural': 'Home pages'},
        ),
    ]
