# Generated by Django 3.2.11 on 2022-03-05 04:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_banner_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, help_text='Add your title', null=True, required=False)), ('text', wagtail.core.blocks.TextBlock(max_length=250, required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn more', max_length=255, required=True))]))], blank=True, null=True),
        ),
    ]
