# Generated by Django 3.2.11 on 2022-03-05 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0010_homepagecarouselimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='carousel_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
