# Generated by Django 3.2.11 on 2022-03-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcribers',
            new_name='Subscriber',
        ),
    ]
